linaro-marketing/connect_automation_container

main.py

Updated the main entry script to simulate --daily-tasks and --upload-video

Updated the main entry script to simulate --daily-tasks and --upload-video 

---

main.py

Removed import that will currently break the build-container tests on bamboo

Removed import that will currently break the build-container tests on bamboo

---

main.py

Updates for simulating the Connect daily-tasks and video-upload options

Updates for simulating the Connect daily-tasks and video-upload options

---

main.py

Updated the script to work with environment variables

Updated the script to work with environment variables

---

.dockerignore
.gitignore
Dockerfile
main.py

Adding connect_youtube_uploader functionality.

Adding connect_youtube_uploader functionality.

---

main.py

Removing the trailing slash from the bamboo_working_directory

Removing the trailing slash from the bamboo_working_directory

---

Dockerfile
app/github_manager.py
app/main.py
aws_config
requirements.txt

Dockerfile:
- ImageMagick added to generated resized images for responsive images on the Connect static website.
- AWS CLI added to sync image asset folders with static-linaro-org s3 bucket.
- Git CLI added for automating the GitHub pull requests with new Jekyll posts
Main.py
- Added run_command(), upload_image_to_s3(), generate_responsive_images() methods
- Updated the jekyll_posts function
github_manager.py
- Added initial class for managing GitHub actions i.e creating pull requests wit the latest Jekyll Posts.

Added ImageMagick/Git/AWS CLI + more

---

.gitconfig
.ssh_config
Dockerfile
app/github_manager.py
app/main.py

This PR adds the automation of GitHub pull requests for changes to Jekyll session posts

GitHub pull requests added for Jekyll Posts

---

Dockerfile

Fixing permissions issues with the work_dir

Fixing permissions issues with the work_dir

---

app/main.py

Updated hardcoded references to the container working directory

Updated hardcoded references to the container working directory

---

app/main.py

Replaced references to the bamboo_working_directory with self.work_directory

Replaced references to the bamboo_working_directory with self.work_directory

---

app/main.py

Updating branch names / paths for the SocialImageGenerator assets/output/templates
Fixes: https://github.com/linaro-marketing/connect_automation_container/issues/30

Updating branch names / paths for the SocialImageGenerator assets/output/templates

---

Dockerfile
app/main.py

Updating branch names / paths for the SocialImageGenerator assets/output/templates #32

 Updating branch names / paths for the SocialImageGenerator assets/output/templates #32 

---

app/main.py

Updated upload-video method and the SocialMediaImageGenerator paths

Updated upload-video method and the SocialMediaImageGenerator paths

---

app/main.py

Adding the custom thumbnail path

Adding the custom thumbnail path

---

app/main.py

Corrected working directory variable name

Corrected working directory variable name

---

app/main.py

Updates to ensure the automation script fails if the creation of the GitHub pull request fails

Updates to ensure the automation script fails if any error occurs

---

app/main.py

Added sys.exit(errorcode) for run_command

Added sys.exit(errorcode) for run_command

---

app/main.py

Add return code status details

Add return code status details

---

app/main.py

Updated the GitHub Manager params

Updated the GitHub Manager params

---

app/main.py

Only rsync over images matching the current event key

Only rsync over images matching the current event key

---

app/main.py

--include flags should go before --exclude

--include flags should go before --exclude

---

app/main.py

Container updates

---

Dockerfile
app/github_manager.py
app/main.py

Updates to ensure changes are made to a single PR / other fixes

Updates to ensure changes are made to a single PR / other fixes

---

app/github_manager.py
app/main.py

Try/Except to catch any errors and reset git repo

Refactored GitHub Manager Script
